### ISSUE TITLE
extra code

### ISSUE THREAD

**Issue by tenSunFree** [merttoptas/BaseApp-Jetpack-Compose-Android-Kotlin#11]
If you want to present the effect of refreshing the screen every time, you can also consider shielding these three lines of code. In addition to achieving the same effect, you can also make the code more concise.
<img width="508" alt="2023-02-25_015144" src="https://user-images.githubusercontent.com/23090085/221253792-70dc0c4e-ec28-4848-a93a-e0bfc6517fcf.png">

**Comment by merttoptas** [comment]
https://github.com/merttoptas/BaseApp-Jetpack-Compose-Android-Kotlin/commit/74a997fa75956eba93460d09165e4426bb5f032c fixed. thank you.
