### ISSUE TITLE
orEmpty() seems redundant

### ISSUE THREAD

**Issue by tenSunFree** [merttoptas/BaseApp-Jetpack-Compose-Android-Kotlin#12]
Because results is a non-null type.
<img width="328" alt="2023-02-27_133010" src="https://user-images.githubusercontent.com/23090085/221482487-05e9b448-8c9f-4abb-b523-77d07d2236c8.png">

So consider removing orEmpty().
<img width="518" alt="2023-02-27_133113" src="https://user-images.githubusercontent.com/23090085/221482510-c7d92615-2844-4791-90fd-beea6ae7c6e8.png">

**Comment by merttoptas** [comment]
https://github.com/merttoptas/BaseApp-Jetpack-Compose-Android-Kotlin/commit/a83e667b7356d8dacb5901dadd6e4ec9076f3e6c 

issue fixed.
