### ISSUE TITLE
The text color of BottomNavigationItem is abnormal

### ISSUE THREAD

**Issue by tenSunFree** [merttoptas/BaseApp-Jetpack-Compose-Android-Kotlin#16]
When other items are not selected, it should be grayed out
![Screenshot_20230305-131200](https://user-images.githubusercontent.com/23090085/222942906-f99c25dc-998a-44e7-b281-2cf455ce961f.png)

Consider adding color = if (selected) primary else secondary
<img width="625" alt="2023-03-05_131108" src="https://user-images.githubusercontent.com/23090085/222942916-e47672ad-e806-45e5-905b-ff450869ed30.png">
![Screenshot_20230305-131135](https://user-images.githubusercontent.com/23090085/222942922-6e8bfc43-8026-4d66-9ba4-4ef7e5cee3de.png)

**Comment by merttoptas** [comment]
https://github.com/merttoptas/BaseApp-Jetpack-Compose-Android-Kotlin/commit/da53dca8a45241f8ec0d7166ad6931d9ec8ab954 fixed, thank you.
