### ISSUE TITLE
Display Error

### ISSUE THREAD

**Issue by tenSunFree** [merttoptas/BaseApp-Jetpack-Compose-Android-Kotlin#9]
When I am on a Google Pixel 6 phone, there will be an abnormal display of the Characters button.
![Screenshot_20230215-132001](https://user-images.githubusercontent.com/23090085/218941865-3c923def-ae2e-4c2c-b20b-902ba6d62160.png)

You can consider adding maxLines = 1 to avoid abnormal display on narrower mobile phones.
<img width="533" alt="2023-02-15_132054" src="https://user-images.githubusercontent.com/23090085/218941913-c26d722a-0376-42aa-8695-ec085a341825.png">

**Comment by merttoptas** [comment]
https://github.com/merttoptas/BaseApp-Jetpack-Compose-Android-Kotlin/commit/34b54f02e21e4edeec0e0c2883a3f18e58a75e32 
fixed. thank you!
